#%RAML 1.0 DataType
type: object
properties:
  Client_Key:
    type: string
  First_Name:
    type: string
  Last_Name:
    type: string
  Birth_Date:
    type: string
  Height:
    type: string
  Weight:
    type: string
  Created_Date:
    type: string
  Billing_Street:
    type: string
  Billing_City:
    type: string
  Billing_State:
    type: string
  Billing_Postal_Code:
    type: string
  Billing_Country:
    type: string
  